### ISSUE TITLE
Development setup for Windows 10 WSL

### ISSUE THREAD

**Issue by michael-mml** [mozilla/firefox-voice#978]
Hi, I'm currently trying to follow the development guide for WSL, but the process seems incomplete. 
Running npm start fails and I cannot find a way to install Firefox Nightly on WSL; I've tried the direct method and extracting the tar.

System: Ubuntu 18.04 on WSL, Windows 10 19041.21

```bash
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/michael/.nvm/versions/node/v13.8.0/bin/node',
1 verbose cli   '/home/michael/.nvm/versions/node/v13.8.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start-and-build'
1 verbose cli ]
2 info using npm@6.13.6
3 info using node@v13.8.0
4 verbose run-script [ 'prestart-and-build', 'start-and-build', 'poststart-and-build' ]
5 info lifecycle firefox-voice@0.19.0~prestart-and-build: firefox-voice@0.19.0
6 info lifecycle firefox-voice@0.19.0~start-and-build: firefox-voice@0.19.0
7 verbose lifecycle firefox-voice@0.19.0~start-and-build: unsafe-perm in lifecycle true
8 verbose lifecycle firefox-voice@0.19.0~start-and-build: PATH: /home/michael/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/michael/firefox-voice/node_modules/.bin:/home/michael/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/michael/firefox-voice/node_modules/.bin:/usr/lib/jvm/java-11-openjdk-amd64/bin:/home/michael/.yarn/bin:/home/michael/.pyenv/plugins/pyenv-virtualenv/shims:/home/michael/.pyenv/shims:/home/michael/.pyenv/bin:/home/michael/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/bin:/usr/lib/jvm/java-11-openjdk-amd64/bin:/home/michael/.nvm/versions/node/v13.8.0/bin:/home/michael/.yarn/bin:/home/michael/.pyenv/plugins/pyenv-virtualenv/shims:/home/michael/.pyenv/shims:/home/michael/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/c/Program Files/AdoptOpenJDK/jdk-11.0.5.10-hotspot/bin:/c/ProgramData/DockerDesktop/version-bin:/c/Program Files/Docker/Docker/Resources/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/c/WINDOWS/System32/OpenSSH/:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/WiFi/bin/:/c/Program Files/Common Files/Intel/WirelessCommon/:/c/Users/michael/AppData/Local/Microsoft/WindowsApps:/c/texlive/2019/bin/win32:/snap/bin:/usr/local/go/bin
9 verbose lifecycle firefox-voice@0.19.0~start-and-build: CWD: /home/michael/firefox-voice
10 silly lifecycle firefox-voice@0.19.0~start-and-build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'NO_SENTRY=1 DEV_ICON=1 npm-run-all maybeinstall build:templates build:manifest start-extension'
10 silly lifecycle ]
11 silly lifecycle firefox-voice@0.19.0~start-and-build: Returned: code: 1  signal: null
12 info lifecycle firefox-voice@0.19.0~start-and-build: Failed to exec start-and-build script
13 verbose stack Error: firefox-voice@0.19.0 start-and-build: `NO_SENTRY=1 DEV_ICON=1 npm-run-all maybeinstall build:templates build:manifest start-extension`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/michael/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/michael/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid firefox-voice@0.19.0
15 verbose cwd /home/michael/firefox-voice
16 verbose Linux 4.19.84-microsoft-standard
17 verbose argv "/home/michael/.nvm/versions/node/v13.8.0/bin/node" "/home/michael/.nvm/versions/node/v13.8.0/bin/npm" "run" "start-and-build"
18 verbose node v13.8.0
19 verbose npm  v6.13.6
20 error code ELIFECYCLE
21 error errno 1
22 error firefox-voice@0.19.0 start-and-build: `NO_SENTRY=1 DEV_ICON=1 npm-run-all maybeinstall build:templates build:manifest start-extension`
22 error Exit status 1
23 error Failed at the firefox-voice@0.19.0 start-and-build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ianb** [comment]
@MLCoco I don't know WSL very well, but I would hope that it could connect with your normal Windows Firefox.

To force the startup to use a particular installation of Firefox, you can do:

```sh
FIREFOX="/mnt/c/Program Files/Mozilla Firefox/firefox.exe" npm start
```

I'm kind of guessing what the right path is, you should of course adjust it for your system.

**Comment by MLCoco** [comment]
You're right about the `$FIREFOX` variable.
I actually got it figured it out for WSL2 and going to make a PR to update the docs.
